language: swift
rvm: 2.3.0
os: osx
osx_image: xcode8.3

before_install:
  - gem install cocoapods
script:
  - xcodebuild -workspace SwiftChatty.xcworkspace -scheme SwiftChatty-iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - xcodebuild -workspace SwiftChatty.xcworkspace -scheme SwiftChatty-OSX CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - xcodebuild -workspace SwiftChatty.xcworkspace -scheme SwiftChatty-tvOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - xcodebuild -workspace SwiftChatty.xcworkspace -scheme SwiftChatty-WatchOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
